Proceso SUMA_NUMEROS
	
	DEFINIR A COMO  ENTERO
	DEFINIR B COMO ENTERO
	DEFINIR SUMA Como ENTERO
	
	//INGRESO DE DATOS
	
	ESCRIBIR " INGRESE PRIMER NÚMERO" 
	LEER A; 
	ESCRIBIR "INGRESE SEGUNDO NÚMERO"
	LEER B;
	
	//MUESTRA DE RESULTADOS SUMA DE NÚMEROS
	
	SUMA = A+B;
	ESCRIBIR " El  resultado de la suma es ",SUMA;
	
	FinAlgoritmo
