Proceso NOMBRE_APELLIDO
	
	DEFINIR NOMBRE COMO  CARACTER
	DEFINIR APELLIDO COMO CARACTER
	
	//INGRESO DE DATOS
	
	ESCRIBIR " INGRESE NOMBRE DE LA PERSONA" 
	LEER NOMBRE; 
	ESCRIBIR "INGRESE APELLIDO DE LA PERSONA"
	LEER APELLIDO;
	
	//MUESTRA DE RESULTADOS
	
	ESCRIBIR NOMBRE,"  ", APELLIDO;
	
FinAlgoritmo
