Proceso EDAD_PERSONA
	//INGRESE EL AÑO DE NACIMIENTO PARA DETERMINAR
	//LA EDAD DE LA UNA PERSONA
	DEFINIR AÑO_NACIMIENTO COMO ENTERO
	DEFINIR ANO_ACTUAL COMO ENTERO
	DEFINIR EDAD COMO ENTERO
	
	ESCRIBIR " INGRESE EL AÑO DE NACIMIENTO" 
	LEER AÑO_NACIMIENTO; 
	ESCRIBIR "INGRESE EL AÑO ACTUAL" 
	LEER AÑO_ACTUAL 
	EDAD = AÑO_ACTUAL - AÑO_NACIMIENTO 
	ESCRIBIR "LA EDAD DE LA PERSONA ES:", EDAD, "AÑOS"
	
FinAlgoritmo
